networks:
  projects:
    name: projects
    external: true
  dev:
    name: dev
    external: true

services:
  subcult-tv-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: subcult-tv-api
    networks: [projects, dev]
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - PORT=8080
      - UMAMI_URL=http://umami:3000
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - PATREON_TOKEN=${PATREON_TOKEN}
      - PATREON_CAMPAIGN_ID=${PATREON_CAMPAIGN_ID}
    labels:
      - com.centurylinklabs.watchtower.enable=false
    restart: unless-stopped

  subcult-tv-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_UMAMI_URL: ${VITE_UMAMI_URL}
        VITE_UMAMI_WEBSITE_ID: ${VITE_UMAMI_WEBSITE_ID}
    container_name: subcult-tv-frontend
    networks: [projects]
    labels:
      - com.centurylinklabs.watchtower.enable=false
    restart: unless-stopped
